//! Native backend for Vladan Toolkit.
//!
//! The frontend talks to Rust through typed IPC commands. Every command is registered in
//! [`specta_builder`], which also generates `src/bindings.ts` so the TypeScript side can
//! never drift from the Rust signatures.

pub mod commands;
pub mod tools;

use tauri::utils::config::{Color, PluginConfig};
use tauri::{AppHandle, Manager, Runtime, WebviewUrl, WebviewWindowBuilder};
use tauri_plugin_window_state::StateFlags;
use tauri_specta::{Builder, ErrorHandlingMode, collect_commands};

/// Generated TypeScript bindings, consumed by the frontend.
pub const BINDINGS_PATH: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../src/bindings.ts");

const BINDINGS_HEADER: &str = "// Generated by tauri-specta from the Rust commands. Do not edit.\n\
// Regenerate with `pnpm bindings` (also happens automatically on `pnpm dev`).\n";

/// Every IPC command the frontend may call. Register new commands here.
#[must_use]
pub fn specta_builder<R: Runtime>() -> Builder<R> {
    Builder::<R>::new()
        .error_handling(ErrorHandlingMode::Throw)
        .commands(collect_commands![
            commands::app::app_info,
            tools::system_info::system_info,
            // new-tool:commands
        ])
}

/// Writes the TypeScript bindings for all registered commands to `path`.
///
/// # Errors
/// Fails if the types cannot be exported or the file cannot be written.
pub fn export_bindings<R: Runtime>(
    builder: &Builder<R>,
    path: impl AsRef<std::path::Path>,
) -> Result<(), specta_typescript::Error> {
    builder.export(
        specta_typescript::Typescript::default().header(BINDINGS_HEADER),
        path,
    )
}

/// The updater is only active when a release build injected `plugins.updater` (with the
/// public key) into the config. Local and CI builds run without it.
#[must_use]
pub fn updater_configured(plugins: &PluginConfig) -> bool {
    plugins
        .0
        .get("updater")
        .and_then(|updater| updater.get("pubkey"))
        .and_then(serde_json::Value::as_str)
        .is_some_and(|key| !key.trim().is_empty())
}

/// Label of the one main window; capabilities are scoped to it.
pub const MAIN_WINDOW: &str = "main";

/// Height of the custom title bar drawn by the frontend (`TitleBar.tsx`, `h-10`).
const TITLE_BAR_HEIGHT: f64 = 40.0;

/// Creates the main window with platform-appropriate chrome:
/// macOS keeps its native traffic lights floating over our title bar; Windows and Linux
/// hide the native frame and the frontend draws minimize/maximize/close itself.
fn create_main_window<R: Runtime>(app: &AppHandle<R>) -> tauri::Result<()> {
    let builder = WebviewWindowBuilder::new(app, MAIN_WINDOW, WebviewUrl::default())
        .title("Vladan Toolkit")
        .inner_size(1200.0, 780.0)
        .min_inner_size(760.0, 520.0)
        .center()
        // Matches `--vt-canvas` so there is no white flash before the UI paints.
        .background_color(Color(11, 10, 8, 255));

    #[cfg(target_os = "macos")]
    let builder = builder
        .title_bar_style(tauri::TitleBarStyle::Overlay)
        .hidden_title(true)
        // tao centers the buttons vertically at `y` from the top of the window.
        .traffic_light_position(tauri::LogicalPosition::new(16.0, TITLE_BAR_HEIGHT / 2.0));

    #[cfg(not(target_os = "macos"))]
    let builder = {
        let _ = TITLE_BAR_HEIGHT;
        builder.decorations(false)
    };

    builder.build()?;
    Ok(())
}

fn focus_main_window<R: Runtime>(app: &AppHandle<R>) {
    if let Some(window) = app.get_webview_window(MAIN_WINDOW) {
        let _ = window.unminimize();
        let _ = window.show();
        let _ = window.set_focus();
    }
}

/// One-time startup: typed events, optional updater, app info, and the main window.
///
/// # Errors
/// Fails if a plugin cannot be initialized or the main window cannot be created.
pub fn setup<R: Runtime>(
    app: &mut tauri::App<R>,
    specta: &Builder<R>,
) -> Result<(), Box<dyn std::error::Error>> {
    specta.mount_events(app);
    let updater_enabled = updater_configured(&app.config().plugins);
    if updater_enabled {
        app.handle()
            .plugin(tauri_plugin_updater::Builder::new().build())?;
    }
    app.manage(commands::app::AppInfo::collect(
        app.handle(),
        updater_enabled,
    ));
    create_main_window(app.handle())?;
    Ok(())
}

/// Builds and runs the application.
pub fn run() {
    let specta = specta_builder::<tauri::Wry>();

    #[cfg(debug_assertions)]
    if let Err(error) = export_bindings(&specta, BINDINGS_PATH) {
        eprintln!("Failed to export TypeScript bindings: {error}");
    }

    let mut builder = tauri::Builder::default();

    // Registered first so a second launch focuses the running instance instead of opening a new one.
    #[cfg(desktop)]
    {
        builder = builder.plugin(tauri_plugin_single_instance::init(|app, _argv, _cwd| {
            focus_main_window(app);
        }));
    }

    builder = builder
        .plugin(
            tauri_plugin_window_state::Builder::new()
                // Decorations come from the per-platform config; visibility is never restored.
                .with_state_flags(StateFlags::all() - StateFlags::DECORATIONS - StateFlags::VISIBLE)
                .build(),
        )
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_process::init());

    #[cfg(feature = "e2e")]
    {
        builder = builder
            .plugin(tauri_plugin_wdio::init())
            .plugin(tauri_plugin_wdio_webdriver::init());
    }

    let handler = specta.invoke_handler();
    let result = builder
        .invoke_handler(handler)
        .setup(move |app| setup(app, &specta))
        .run(tauri::generate_context!());

    if let Err(error) = result {
        eprintln!("Vladan Toolkit failed to start: {error}");
        std::process::exit(1);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;
    use tauri::test::{mock_builder, mock_context, noop_assets};

    fn mock_app(plugins: serde_json::Value) -> tauri::App<tauri::test::MockRuntime> {
        let mut context = mock_context(noop_assets());
        context.config_mut().plugins =
            PluginConfig(serde_json::from_value(plugins).unwrap_or_default());
        mock_builder()
            .build(context)
            .unwrap_or_else(|e| panic!("failed to build app: {e}"))
    }

    #[test]
    fn setup_creates_the_main_window_without_updater() {
        let mut app = mock_app(json!({}));
        setup(&mut app, &specta_builder()).unwrap_or_else(|e| panic!("setup failed: {e}"));
        assert!(app.get_webview_window(MAIN_WINDOW).is_some());
        assert!(!app.state::<commands::app::AppInfo>().updater_enabled);
        // A second launch focuses the existing window instead of opening another one.
        focus_main_window(app.handle());
        assert_eq!(app.webview_windows().len(), 1);
    }

    #[test]
    fn setup_enables_updater_when_configured() {
        let mut app = mock_app(json!({
            "updater": {
                "pubkey": "dW50cnVzdGVkIGNvbW1lbnQ=",
                "endpoints": ["https://example.com/latest.json"]
            }
        }));
        setup(&mut app, &specta_builder()).unwrap_or_else(|e| panic!("setup failed: {e}"));
        assert!(app.state::<commands::app::AppInfo>().updater_enabled);
    }

    fn plugins(value: serde_json::Value) -> PluginConfig {
        PluginConfig(serde_json::from_value(value).unwrap_or_default())
    }

    #[test]
    fn updater_disabled_without_config() {
        assert!(!updater_configured(&plugins(json!({}))));
    }

    #[test]
    fn updater_disabled_with_empty_pubkey() {
        assert!(!updater_configured(&plugins(
            json!({ "updater": { "pubkey": "  " } })
        )));
    }

    #[test]
    fn updater_enabled_with_pubkey() {
        assert!(updater_configured(&plugins(
            json!({ "updater": { "pubkey": "dW50cnVzdGVkIGNvbW1lbnQ=" } })
        )));
    }

    /// Fails when a command signature changed but `src/bindings.ts` was not regenerated.
    /// Run `pnpm bindings` to update the file.
    #[test]
    fn bindings_are_up_to_date() {
        let builder = specta_builder::<tauri::test::MockRuntime>();
        if std::env::var_os("UPDATE_BINDINGS").is_some() {
            export_bindings(&builder, BINDINGS_PATH)
                .unwrap_or_else(|e| panic!("export failed: {e}"));
            return;
        }
        let dir = std::env::temp_dir().join(format!("vt-bindings-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap_or_else(|e| panic!("temp dir: {e}"));
        let fresh_path = dir.join("bindings.ts");
        export_bindings(&builder, &fresh_path).unwrap_or_else(|e| panic!("export failed: {e}"));
        let fresh = std::fs::read_to_string(&fresh_path).unwrap_or_default();
        let committed = std::fs::read_to_string(BINDINGS_PATH).unwrap_or_default();
        let _ = std::fs::remove_dir_all(&dir);
        assert!(
            fresh == committed,
            "src/bindings.ts is out of date. Run `pnpm bindings` and commit the result."
        );
    }
}
