// Generated by tauri-specta from the Rust commands. Do not edit.
// Regenerate with `pnpm bindings` (also happens automatically on `pnpm dev`).

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**
	 *  Collects the snapshot on a blocking worker thread.
	 * 
	 *  # Errors
	 *  Returns an error if the worker thread panicked.
	 */
	systemInfo: () => __TAURI_INVOKE<SystemInfo>("system_info"),
};

/* Types */
/**
 *  Static information about the running build, shown in Settings → About.
 *  Computed once at startup and served from managed state.
 */
export type AppInfo = {
	name: string,
	version: string,
	tauriVersion: string,
	webviewVersion: string | null,
	os: string,
	arch: string,
	updaterEnabled: boolean,
};

/**  A snapshot of the host machine. Sizes are `f64` because TypeScript numbers are doubles. */
export type SystemInfo = {
	osName: string | null,
	osVersion: string | null,
	kernelVersion: string | null,
	arch: string,
	cpuBrand: string | null,
	logicalCores: number,
	physicalCores: number | null,
	totalMemoryBytes: number | null,
	uptimeSeconds: number | null,
};

